// This file is auto-generated by tools/updateVersion.js. Do not edit directly.
export const VERSION = "1.0.10";
export const REPO_URL = "https://github.com/deftio/squibview";

export default { version: VERSION, url: REPO_URL };
