// This file is auto-generated by tools/updateVersion.js. Do not edit directly.
export const VERSION = "0.0.39-dev.5";
export const REPO_URL = "https://github.com/deftio/squibview";

export default { version: VERSION, url: REPO_URL };
